## Ejercicios - Algebra

In [1]:
import numpy as np

import random

In [2]:
# Versiones
print(f"numpy=={np.__version__}")

numpy==2.2.0


### Ejercicio 1:
- Usando la librería _**random**_, genera una matriz de $4x4$ de números enteros del 1 al 100, usando bucles.
- El resultado debe ser un _**np.array()**_.

In [3]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape)  #primero da las filas y luego las columnas

[[1 2 3]
 [1 2 3]]
(2, 3)


In [4]:
# en el ejercicio se pide 4x4


In [5]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape)  #primero da las filas y luego las columnas
# Uso de bucles for para crear una lista en Python y pasarla a array de numpy

[[1 2 3]
 [1 2 3]]
(2, 3)


In [6]:
matriz = list()
import random
for i in range(4):
    fila = list()
    for j in range(4):
        # numero_aleatorio = 1  para descomponer el problema en partes y ver si funciona
        # numero_aleatorio = j       
        numero_aleatorio = random.randint(1, 100)
        fila.append(numero_aleatorio)
        
    matriz.append(fila)
     
print(matriz)    
np.array(matriz)


[[51, 88, 94, 19], [23, 69, 46, 82], [69, 59, 68, 43], [89, 13, 33, 8]]


array([[51, 88, 94, 19],
       [23, 69, 46, 82],
       [69, 59, 68, 43],
       [89, 13, 33,  8]])

In [7]:
#se puede poner comprimido:
np.array([[random.randint(1, 100) for j in range(4)] for i in range(4)])

array([[87, 77, 90,  9],
       [61, 57,  1, 63],
       [97, 20, 79, 77],
       [86, 19, 21,  3]])

### Ejercicio 2:

- Define una función que tome como parámetro de entrada 2 valores enteros ($m$, $n$).
- La función debe generar, usando la librería _**random**_, una matriz de $mxn$ de números enteros del 1 al 100, usando bucles.
- La función debe retornar la matriz, la matriz debe ser un _**np.array()**_.

In [26]:
# en este caso es una matriz dinamica, de mxn
# hay que crear una función
def generar_matriz(m=4, n=4): # añadiendo un valor nos aseguramos que al menos tendrá estas dimensiones si se introducen m y n mal
    matriz = []
    if m<=0 or n<=0:
        raise ValueError("Dimensiones incorrectas")
    
    for i in range(m):
        fila = []
        for j in range(n):
            numero_aleatorio = random.randint(1, 100)
            fila.append(numero_aleatorio)
        
        matriz.append(fila)
    return np.array(matriz)

generar_matriz(4, 6)


array([[89, 15, 44, 50, 30, 30],
       [ 7, 82, 84, 22, 89, 37],
       [ 1, 61, 35, 26, 60, 87],
       [28, 84, 95, 71, 33, 82]])

In [9]:
##############################################################################################################################